# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: albatross-example-root-password
      MARIADB_DATABASE: albatross
      MARIADB_USER: indexer
      MARIADB_PASSWORD: indexer-password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo:7-jammy
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: albatross
      MONGO_INITDB_ROOT_PASSWORD: "safepasswordorsomething"
      MONGO_INITDB_DATABASE: albatross
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: albatross
      ME_CONFIG_MONGODB_ADMINPASSWORD: "safepasswordorsomething"
      ME_CONFIG_MONGODB_URL: "mongodb://albatross:safepasswordorsomething@mongo:27017/"