# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: albatross
      MONGO_INITDB_ROOT_PASSWORD: "safepasswordorsomething"
      MONGO_INITDB_DATABASE: albatross
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: albatross
      ME_CONFIG_MONGODB_ADMINPASSWORD: "safepasswordorsomething"
      ME_CONFIG_MONGODB_URL: "mongodb://albatross:safepasswordorsomething@mongo:27017/"